### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by smyang10** [toradex/microsoft-ecosystem-environment-documentation#1]
Following the instructions, I am getting this error:
![image](https://user-images.githubusercontent.com/9678640/70365341-c1b69580-1845-11ea-89f9-c7312cdbc08b.png)

Can't find any information on what is causing it. Visual Studio 2017 15.9, Docker 2.1.0.5, Colibri iMX6.

Attempting to connect via IP results in 
![image](https://user-images.githubusercontent.com/9678640/70365369-e7dc3580-1845-11ea-9499-95201bfd7530.png)

**Comment by VMinute** [comment]
The visual studio plugin talks with a server application named moses.exe on port 5000, check that your antivirus/personal firewall is not blocking local traffic on that port and/or communication between applications on the same machine.

**Comment by smyang10** [comment]
> The visual studio plugin talks with a server application named moses.exe on port 5000, check that your antivirus/personal firewall is not blocking local traffic on that port and/or communication between applications on the same machine.

Thanks that was it. I had another application running on my machine that was using port 5000.
